### ISSUE TITLE
[QUESTION] Can it be built on GNU/Linux?

### ISSUE THREAD

**Issue by neoapps-dev** [liriliri/aya#1]
title :/

I'm pretty sure the answer is yes, but I still wanna see your answer :)

**Comment by parkerlreed** [comment]
`npm run build` fails to find adb in current folder so you have to manually copy it.

After building the server with java 17 using the gradlew script

`npm run build` thjen fails with

```
[Error: ENOENT: no such file or directory, lstat 'server/aya.dex'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'server/aya.dex'
}
```

No idea how to make this file, especially with no build instructions :( I'm just guessing at all of this.

**Comment by parkerlreed** [comment]
I seem to have gotten an AppImage/unpacked folder after running `npm run pack`

But it never starts/fails to find the server on http://localhost:8080/

![image](https://github.com/user-attachments/assets/ecbc0063-afd8-4c65-a098-4aab8f87a16f)

**Comment by parkerlreed** [comment]
I ran through all the `npm run build:*` again and it seems to have started this time!

![image](https://github.com/user-attachments/assets/7fe1cc0e-e40b-45f7-b8dd-e5d537addf13)

**Comment by LinuxSBC** [comment]
As a suggestion, maybe build it as an AppImage or Flatpak. A Flatpak runs on any distro and could be uploaded to Flathub so it's right in the user's app store, and an AppImage is like a portable EXE—it runs on every distro, but requires something like [Gear Lever](https://flathub.org/apps/it.mijorus.gearlever) to actually install it.

**Comment by parkerlreed** [comment]
AppImage is already the default build configuration. That's what I'm runnin above.

**Comment by surunzi** [comment]
I don't have a Linux machine, currently trying to use GitHub Actions to compile a version for the Linux platform.

**Comment by surunzi** [comment]
I just built a Linux AppImage version. Can someone test it to see if it works properly? https://github.com/liriliri/aya/releases/tag/v0.1.0

**Comment by neoapps-dev** [comment]
Oooh! Thank you guys!

**Comment by parkerlreed** [comment]
> I just built a Linux AppImage version. Can someone test it to see if it works properly? https://github.com/liriliri/aya/releases/tag/v0.1.0

Works great! Thank you.
